// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieTickets.Data;

#nullable disable

namespace MovieTickets.Data.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20230811210919_Seed")]
    partial class Seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MovieTickets.Data.EntityModels.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Ryan Rodney Reynolds OBC is a Canadian and American actor, film producer, and businessman. He began his career starring in the Canadian teen soap opera Hillside, and had minor roles before landing the lead role on the sitcom Two Guys and a Girl between 1998 and 2001.",
                            ImageUrl = "https://pics.filmaffinity.com/ryan_reynolds-279844037918521-nm_large.jpg",
                            Name = "Ryan Reynolds"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Jacob Benjamin Gyllenhaal is an American actor. Born into the Gyllenhaal family, he is the son of director Stephen Gyllenhaal and screenwriter Naomi Foner, and his older sister is actress Maggie Gyllenhaal.",
                            ImageUrl = "https://pics.filmaffinity.com/jake_gyllenhaal-173579980188358-nm_large.jpg",
                            Name = "Jake Gyllenhaal"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Rebecca Louisa Ferguson Sundström is a Swedish actress. She began her acting career with the Swedish soap opera Nya tider and went on to star in the slasher film Drowning Ghost.",
                            ImageUrl = "https://pics.filmaffinity.com/rebecca_ferguson-273006559554882-nm_200.jpg",
                            Name = "Rebecca Ferguson"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Christian Charles Philip Bale is an English actor. Known for his versatility and physical transformations for his roles, he has been a leading man in films of several genres. He has received various accolades, including an Academy Award and two Golden Globe Awards.",
                            ImageUrl = "https://pics.filmaffinity.com/christian_bale-146362426279095-nm_large.jpg",
                            Name = "Christian Bale"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Aaron Edward Eckhart is an American actor. Born in Cupertino, California, Eckhart moved to the United Kingdom at an early age. He began his acting career by performing in school plays, before moving to Australia for his high school senior year.",
                            ImageUrl = "https://pics.filmaffinity.com/aaron_eckhart-072135910642502-nm_large.jpg",
                            Name = "Aaron Eckhart"
                        });
                });

            modelBuilder.Entity("MovieTickets.Data.EntityModels.ActorMovie", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("ActorMovies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            ActorId = 1
                        },
                        new
                        {
                            MovieId = 1,
                            ActorId = 3
                        },
                        new
                        {
                            MovieId = 2,
                            ActorId = 1
                        },
                        new
                        {
                            MovieId = 2,
                            ActorId = 4
                        },
                        new
                        {
                            MovieId = 3,
                            ActorId = 1
                        },
                        new
                        {
                            MovieId = 3,
                            ActorId = 2
                        },
                        new
                        {
                            MovieId = 3,
                            ActorId = 5
                        },
                        new
                        {
                            MovieId = 4,
                            ActorId = 2
                        },
                        new
                        {
                            MovieId = 4,
                            ActorId = 3
                        },
                        new
                        {
                            MovieId = 4,
                            ActorId = 4
                        },
                        new
                        {
                            MovieId = 5,
                            ActorId = 2
                        },
                        new
                        {
                            MovieId = 5,
                            ActorId = 3
                        },
                        new
                        {
                            MovieId = 5,
                            ActorId = 4
                        },
                        new
                        {
                            MovieId = 5,
                            ActorId = 5
                        },
                        new
                        {
                            MovieId = 6,
                            ActorId = 3
                        },
                        new
                        {
                            MovieId = 6,
                            ActorId = 4
                        },
                        new
                        {
                            MovieId = 6,
                            ActorId = 5
                        });
                });

            modelBuilder.Entity("MovieTickets.Data.EntityModels.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MovieTickets.Data.EntityModels.Cinema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Street")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Cinemas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Sofia",
                            Country = "Bulgaria",
                            Description = "We've got 5 screens of film magic, all screening stunning RealD 3D and perfectly located on the Top floor of the Sofia Mill Superstore.For those who love life behind the wheel, you can pick you perfect parking spot in the underground car park outside.",
                            LogoUrl = "https://www1.lovethatdesign.com/wp-content/uploads/2019/03/Love-that-Design-NOVO-13-1024x623.jpg",
                            Name = "Cinema Sofia",
                            Street = "ul.Bulgaria 10"
                        },
                        new
                        {
                            Id = 2,
                            City = "Plovdiv",
                            Country = "Bulgaria",
                            Description = "We've got 5 screens of film magic, all screening stunning RealD 3D and perfectly located on the Top floor of the Sofia Mill Superstore.For those who love life behind the wheel, you can pick you perfect parking spot in the underground car park outside.",
                            LogoUrl = "https://whatson.ae/wp-content/uploads/2019/02/innerNovo-high-res-07.jpg",
                            Name = "Cinema Plovdiv",
                            Street = "ul.Plovdiv 10"
                        },
                        new
                        {
                            Id = 3,
                            City = "Varna",
                            Country = "Bulgaria",
                            Description = "We've got 5 screens of film magic, all screening stunning RealD 3D and perfectly located on the Top floor of the Sofia Mill Superstore.For those who love life behind the wheel, you can pick you perfect parking spot in the underground car park outside.",
                            LogoUrl = "https://www1.lovethatdesign.com/wp-content/uploads/2019/03/Love-that-Design-NOVO-04.jpg",
                            Name = "Cinema Varna",
                            Street = "ul.Varna 10"
                        },
                        new
                        {
                            Id = 4,
                            City = "Burgas",
                            Country = "Bulgaria",
                            Description = "We've got 5 screens of film magic, all screening stunning RealD 3D and perfectly located on the Top floor of the Sofia Mill Superstore.For those who love life behind the wheel, you can pick you perfect parking spot in the underground car park outside.",
                            LogoUrl = "https://img.freepik.com/free-vector/movie-home-curtains-cinema-seats_1419-1853.jpg?w=2000",
                            Name = "Cinema Burgas",
                            Street = "ul.Burgas 10"
                        },
                        new
                        {
                            Id = 5,
                            City = "Smolyan",
                            Country = "Bulgaria",
                            Description = "We've got 5 screens of film magic, all screening stunning RealD 3D and perfectly located on the Top floor of the Sofia Mill Superstore.For those who love life behind the wheel, you can pick you perfect parking spot in the underground car park outside.",
                            LogoUrl = "https://img.freepik.com/free-vector/movie-home-curtains-cinema-seats_1419-1853.jpg?w=2000",
                            Name = "Cinema Smolyan",
                            Street = "ul.Smolyan 10"
                        });
                });

            modelBuilder.Entity("MovieTickets.Data.EntityModels.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CinemaId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("MovieCategory")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("ProducerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CinemaId");

                    b.HasIndex("ProducerId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CinemaId = 3,
                            Description = "As astronauts discover the first evidence of extra-terrestrial life on Mars, they begin realising that the life form is extremely intelligent and hostile.",
                            EndDate = new DateTime(2023, 8, 22, 0, 9, 18, 868, DateTimeKind.Local).AddTicks(8098),
                            ImageUrl = "https://pics.filmaffinity.com/Life-707248688-large.jpg",
                            MovieCategory = 4,
                            Price = 39m,
                            ProducerId = 3,
                            StartDate = new DateTime(2023, 8, 2, 0, 9, 18, 868, DateTimeKind.Local).AddTicks(8059),
                            Title = "Life"
                        },
                        new
                        {
                            Id = 2,
                            CinemaId = 1,
                            Description = "Batman/Bruce Wayne (Christian Bale) raises the stakes in his war on crime. With the help of Lieutenant Jim Gordon (Gary Oldman) and District Attorney Harvey Dent (Aaron Eckhart), Batman sets out to dismantle the remaining criminal organizations that plague the city streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as The Joker (Heath Ledger).",
                            EndDate = new DateTime(2023, 8, 15, 0, 9, 18, 868, DateTimeKind.Local).AddTicks(8107),
                            ImageUrl = "https://pics.filmaffinity.com/The_Dark_Knight-102763119-large.jpg",
                            MovieCategory = 1,
                            Price = 29m,
                            ProducerId = 1,
                            StartDate = new DateTime(2023, 8, 12, 0, 9, 18, 868, DateTimeKind.Local).AddTicks(8105),
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 3,
                            CinemaId = 4,
                            Description = "Michael Jennings (Ben Affleck) is a high-paid engineer who works on hush-hush computer inventions and technology for shady companies. Later, his memory is wiped clean, so he has no recollection of his work. His so-called friend Rethrick (Aaron Eckhardt) offers him enough money to retire by working on a project at Rethrick's company, Allcom. When Jennings emerges three years later, sans memory, he tries to collect his paycheck. At the bank, he's handed a manila envelope filled with cryptic items he doesn't recognize, and told he voluntarily forfeited his entire paycheck. He also has a stunning girlfriend named Dr. Rachel Porter (Uma Thurman) who is likewise ensnared in the conspiracy. Jennings must somehow piece together the clues he left for himself, and find out why everyone is out to kill him... Adapted from a mind-bending sci-fi thriller novel by Philip K. Dick.",
                            EndDate = new DateTime(2023, 8, 19, 0, 9, 18, 868, DateTimeKind.Local).AddTicks(8114),
                            ImageUrl = "https://pics.filmaffinity.com/Paycheck-957568097-large.jpg",
                            MovieCategory = 7,
                            Price = 19m,
                            ProducerId = 4,
                            StartDate = new DateTime(2023, 8, 12, 0, 9, 18, 868, DateTimeKind.Local).AddTicks(8112),
                            Title = "Paycheck"
                        },
                        new
                        {
                            Id = 4,
                            CinemaId = 1,
                            Description = "A young CIA agent is tasked with looking after a fugitive in a safe house. But when the safe house is attacked, he finds himself on the run with his charge.",
                            EndDate = new DateTime(2023, 8, 7, 0, 9, 18, 868, DateTimeKind.Local).AddTicks(8120),
                            ImageUrl = "https://pics.filmaffinity.com/Safe_House-299293074-large.jpg",
                            MovieCategory = 4,
                            Price = 49m,
                            ProducerId = 2,
                            StartDate = new DateTime(2023, 8, 2, 0, 9, 18, 868, DateTimeKind.Local).AddTicks(8118),
                            Title = "Safe House"
                        },
                        new
                        {
                            Id = 5,
                            CinemaId = 1,
                            Description = "When Guy, a bank teller, learns that he is a non-player character in a bloodthirsty, open-world video game, he goes on to become the hero of the story and takes the responsibility of saving the world.",
                            EndDate = new DateTime(2023, 8, 10, 0, 9, 18, 868, DateTimeKind.Local).AddTicks(8125),
                            ImageUrl = "https://pics.filmaffinity.com/Free_Guy-297648487-large.jpg",
                            MovieCategory = 2,
                            Price = 59m,
                            ProducerId = 3,
                            StartDate = new DateTime(2023, 8, 2, 0, 9, 18, 868, DateTimeKind.Local).AddTicks(8123),
                            Title = "Free Guy"
                        },
                        new
                        {
                            Id = 6,
                            CinemaId = 1,
                            Description = "Father Gabriele Amorth, chief exorcist for the Vatican, battles Satan and innocent-possessing demons. A detailed portrait of a priest who performed more than 100,000 exorcisms in his lifetime.",
                            EndDate = new DateTime(2023, 9, 1, 0, 9, 18, 868, DateTimeKind.Local).AddTicks(8132),
                            ImageUrl = "https://pics.filmaffinity.com/The_Pope_s_Exorcist-660382735-large.jpg",
                            MovieCategory = 3,
                            Price = 79m,
                            ProducerId = 5,
                            StartDate = new DateTime(2023, 8, 15, 0, 9, 18, 868, DateTimeKind.Local).AddTicks(8130),
                            Title = "The Pope's Exorcist"
                        });
                });

            modelBuilder.Entity("MovieTickets.Data.EntityModels.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MovieTickets.Data.EntityModels.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("MovieTickets.Data.EntityModels.Producer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Producers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Jorge Daniel Espinosa is a Swedish-Chilean film director, screenwriter and film producer from Trångsund, Stockholm. He graduated from the National Film School of Denmark in 2001. He notably directed the Sony's Marvel Universe film Morbius starring Jared Leto and other films including Life, Easy Money, The Boxer, Babylon Disease, Outside Love and Child 44.",
                            ImageUrl = "https://pics.filmaffinity.com/daniel_espinosa-161586443111622-nm_large.jpg",
                            Name = "Daniel Espinosa"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Best known for his cerebral, often nonlinear, storytelling, acclaimed writer-director Christopher Nolan was born on July 30, 1970, in London, England. Over the course of 15 years of filmmaking, Nolan has gone from low-budget independent films to working on some of the biggest blockbusters ever made.",
                            ImageUrl = "https://pics.filmaffinity.com/christopher_nolan-055100338198118-nm_large.jpg",
                            Name = "Christopher Nolan"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Born in southern China, John Woo grew up in Hong Kong, where he began his film career as an assistant director in 1969, working for Shaw Brothers Studios. He directed his first feature in 1973 and has been a prolific director ever since, working in a wide variety of genres before A Better Tomorrow (1986) established his reputation as a master stylist specializing in ultra-violent gangster films and thrillers, with hugely elaborate action scenes shot with breathtaking panache. After gaining a cult reputation in the US with The Killer (1989), Woo was offered a Hollywood contract. He now works in the US.",
                            ImageUrl = "https://pics.filmaffinity.com/john_woo-168005725142890-nm_large.jpg",
                            Name = "John Woo"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Shawn Levy was born on July 23, 1968 in Montreal, Quebec, Canada. He is a producer and director, known for Stranger Things (2016), Real Steel (2011), and the Night at the Museum franchise. He is the founder and principal of 21 Laps Entertainment. He is married to Serena Levy and they have four daughters.",
                            ImageUrl = "https://pics.filmaffinity.com/shawn_levy-200697726875313-nm_large.jpg",
                            Name = "Shawn Levy"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Julius Avery is an Australian screenwriter and film director.",
                            ImageUrl = "https://pics.filmaffinity.com/julius_avery-142054011329446-nm_large.jpg",
                            Name = "Julius Avery"
                        });
                });

            modelBuilder.Entity("MovieTickets.Data.EntityModels.ShoppingCartItems", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingCartId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("MovieTickets.Data.EntityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("MovieTickets.Data.EntityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieTickets.Data.EntityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("MovieTickets.Data.EntityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieTickets.Data.EntityModels.ActorMovie", b =>
                {
                    b.HasOne("MovieTickets.Data.EntityModels.Actor", "Actor")
                        .WithMany("ActorMovies")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieTickets.Data.EntityModels.Movie", "Movie")
                        .WithMany("ActorMovies")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieTickets.Data.EntityModels.Movie", b =>
                {
                    b.HasOne("MovieTickets.Data.EntityModels.Cinema", "Cinema")
                        .WithMany("Movies")
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieTickets.Data.EntityModels.Producer", "Producer")
                        .WithMany("Movies")
                        .HasForeignKey("ProducerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinema");

                    b.Navigation("Producer");
                });

            modelBuilder.Entity("MovieTickets.Data.EntityModels.Order", b =>
                {
                    b.HasOne("MovieTickets.Data.EntityModels.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieTickets.Data.EntityModels.OrderItem", b =>
                {
                    b.HasOne("MovieTickets.Data.EntityModels.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieTickets.Data.EntityModels.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MovieTickets.Data.EntityModels.ShoppingCartItems", b =>
                {
                    b.HasOne("MovieTickets.Data.EntityModels.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieTickets.Data.EntityModels.Actor", b =>
                {
                    b.Navigation("ActorMovies");
                });

            modelBuilder.Entity("MovieTickets.Data.EntityModels.Cinema", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("MovieTickets.Data.EntityModels.Movie", b =>
                {
                    b.Navigation("ActorMovies");
                });

            modelBuilder.Entity("MovieTickets.Data.EntityModels.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("MovieTickets.Data.EntityModels.Producer", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
